language: go
dist: trusty
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

go:
  - "1.11.x"
go_import_path: git.code.oa.com/gaiastack/galaxy

install: true

env:
  - CODECOV_TOKEN=f29f8f5a-9a4c-44ad-bfc9-85f24e7c2d61 TEST_ENV=linux_root

before_script:
  - go get -u github.com/Masterminds/glide
  - go get -u github.com/onsi/ginkgo/ginkgo
  - curl -L https://git.io/vp6lP | sh /dev/stdin -b $GOPATH/bin
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -proot
  - sudo service mysql restart

script:
  - hack/verify.sh
  - hack/build.sh
  - hack/build-ipam.sh
  - gometalinter cni/... cmd/... pkg/... tools/...
  - sudo -E env "PATH=$PATH" hack/test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash) uuid-repo-token
