apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: floatips.galaxy.k8s.io
spec:
  group: galaxy.k8s.io
  version: v1alpha1
  names:
    kind: FloatIp
    plural: floatips
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pools.galaxy.k8s.io
spec:
  group: galaxy.k8s.io
  version: v1alpha1
  names:
    kind: Pool
    plural: pools
  scope: Namespaced